---
version: "2.0"

services:
  ghost:
    image: ghost:5.12.3
    expose:
      - port: 2368
        as: 80
        to:
          - global: true
        accept:
          - changeme.com
    env:
      - url=http://changeme.com
      - NODE_ENV=production
      # ref. https://ghost.org/docs/config/#configuration-options
      - database__client=sqlite3
      - database__connection__filename=content/data/ghost.db

profiles:
  compute:
    ghost:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 5Gi
  placement:
    akash:
      pricing:
        ghost:
          denom: uakt
          amount: 10000

deployment:
  ghost:
    akash:
      profile: ghost
      count: 1
