name: Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Release Variables
        id: vars
        uses: ignite/cli/actions/release/vars@main
      - name: build
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build . --tag ghcr.io/${{ github.repository }}::$(date +%s) -f docker/Dockerfile
          docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag_name }}
