name: Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker build . --tag ghcr.io/${{ github.repository }}:$(date +%s)
          docker push ghcr.io/${{ github.repository }}:$(date +%s)
